### ISSUE TITLE
Pixel 9 pro xl Aborted: no 7.0 audio policy implementation

### ISSUE THREAD

**Issue by g1nt0** [yzyhk904/audio-samplerate-changer#1]
- Copying zip to temp directory
- Installing magisk-module-audio-samplerate-changer-v1.0.1.zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
**************************
 Audio samplerate changer 
 by zyhk 
**************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: changelog.md
  inflating: customize-functions.sh
  inflating: jitter-reducer-functions.shlib
  inflating: LICENSE
  inflating: module.prop
  inflating: README.md
  inflating: service-functions.sh
  inflating: service.sh
   creating: system/
  inflating: system.prop
   creating: templates/
  inflating: templates/bypass_offload_template.xml
  inflating: templates/offload_hifi_playback_template.xml
  inflating: customize.sh
  ***
  Aborted: no 7.0 audio policy implementation; this module doesn't support old devices based on pre 7.0 audio implementations
  ***
! Installation failed

**Comment by yzyhk904** [comment]
Do you know where ``android.hardware.audio@7.1.so`` exists? I cannot fix this issue without this info because I don't have Pixel 9 PRO X.

I've heard about Pixel9 that some libraries in "/vendor/lib64" have been moved into "/system". If the above library is such, try [this testing magisk-module-audio-samplerate-changer.zip](https://github.com/user-attachments/files/17587118/magisk-module-audio-samplerate-changer.zip).

**Comment by g1nt0** [comment]
same result with test module...

I couldn't find this file, only 6.0 in system/lib64
![Screenshot_20241031-143216](https://github.com/user-attachments/assets/d5461d02-44ff-447c-b7cb-0e9a9ded7fd3)

**Comment by yzyhk904** [comment]
This module cannot run on AIDL only devices like Pixel 9 series. I will add another warning for such devices.

**Comment by 3ndrop4in** [comment]
Got similar problem with lineage 21 OS for Poco F4. Is it because I use nightly bulid? 
Found it,  but in system/lib64 and it's 6.0 version.

**Comment by yzyhk904** [comment]
I made a root (or adb) script checking the audio configuration on your devices. Please unzip [CheckAudioConfiguration.zip](https://github.com/user-attachments/files/17607045/CheckAudioConfiguration.zip) and execute `sh ./CheckAudioConfiguration.sh`.

I'm fixing in some situations, e.g., using A13 or later GSI's (7.1 imp. under /system/lib64) and possibly some custom ROM's (the same). If you like, try [testing magisk-module-audio-samplerate-changer.zip](https://github.com/user-attachments/files/17607030/magisk-module-audio-samplerate-changer.zip).

**Comment by 3ndrop4in** [comment]
Ok. This is the output. 
![Screenshot1](https://github.com/user-attachments/assets/a276594c-f0f3-4dca-aa5a-1bf4eb48923c)

**Comment by yzyhk904** [comment]
There isn't any Android devices having no "/system/bin/dumpsys"! The settings of you terminal emulator is something wrong. Restricted to be toybox command only?

By looking into sources of LineageOS, I think your device has pre 7.0 audio configuration only.

**Comment by 3ndrop4in** [comment]
Unfortunately. Couldn't find the file you mentioned android.hardware.audio@7.1.so Too bad. It would be great to use your script. Thanks for the effort. Hopefully my next phone will have that policy enabled. I am not very proficient in using Termux, so there is a chance that I may do something wrong.

**Comment by yzyhk904** [comment]
Sorry. 

If you dare to install TD GSI over LineageOS on your device, you could use this module.
