### ISSUE TITLE
Lost ability to control volume when playing audio jack

### ISSUE THREAD

**Issue by gladykov** [yzyhk904/audio-samplerate-changer#2]
When playing audio through audio jack, volume is maxed and cannot be controlled with volume keys. Does not happen on speakers.

Tried both Spotify and Tidal

Asus ZenFone 9 / Android 14

Module version: v1.0.2

This does not occur when using standalone DRC Remover

**Comment by yzyhk904** [comment]
It seems that Zenfone 9 has audio volume settings whose file names are unusual. I made new module including typical volume settings (maybe different from device specific ones a bit).

Try this module [magisk-module-audio-samplerate-changer.zip](https://github.com/user-attachments/files/17632517/magisk-module-audio-samplerate-changer.zip).

**Comment by gladykov** [comment]
Attached module didn't help. Let me know if I can help debug.

**Comment by yzyhk904** [comment]
I made another module including extra volume curves for an EU regulation. Try this [magisk-module-audio-samplerate-changer.zip](https://github.com/user-attachments/files/17647351/magisk-module-audio-samplerate-changer.zip).

If this module doesn't work, attach here your audio_policy_configuration.xml and audio_policy_volumes*.xml. Execute this root script [CheckAudioConfiguration.zip](https://github.com/user-attachments/files/17647395/CheckAudioConfiguration.zip) (unzip and execute sh ./CheckAudioConfiguration.sh with root permission), and your get a path to the XML file. The volumes files are liked in this XML file.

**Comment by gladykov** [comment]
Thank you. Will try during the weekend and report back

**Comment by gladykov** [comment]
Latest module didn't work either. Volume is still maxed out when phone jack is connected.  I'm attaching `/vendor/etc/audio/DAVINCI/audio_policy_configuration_AI2202.xml` and other files, which may be helpful.

[audio_policies_asus_9.zip](https://github.com/user-attachments/files/17684808/audio_policies_asus_9.zip)

( I had to ZIP them as Github does not allow XML )

**Comment by yzyhk904** [comment]
I made another module again including non-EU volume curves for headsets. Try [magisk-module-audio-samplerate-changer.zip](https://github.com/user-attachments/files/17687904/magisk-module-audio-samplerate-changer.zip).

**Comment by gladykov** [comment]
Thank you! Now it worked and I can change the volume both with jack and speaker, and with and without `audio misc. settings` module.

**Comment by yzyhk904** [comment]
Good news! I'll modify this module to adjust the volume links by searching existing volume XML files on each device. There may be other devices that place the volume files (specific to each device property) unusually.

**Comment by gladykov** [comment]
Thank you!

**Comment by yzyhk904** [comment]
I uploaded the latest release version fixed for your issue
