### ISSUE TITLE
Youtube stuttering

### ISSUE THREAD

**Issue by yabo-boye** [yzyhk904/audio-samplerate-changer#3]
YouTube video streaming starts to stutter and is not playable,  no audio

**Comment by yzyhk904** [comment]
I think you are using the streaming with internal speakers. My module sets the samplerate of the speakers to be 384 kHz and I guess YouTube video cannot handle the 384 kHz.

See README!

**Comment by yabo-boye** [comment]
True. On headphones it works. Also audio from WhatsApp etc doesn't work on internal speakers.  Would be possible to leave internal speakers without change, as they are shit anyway?

I have also flash resampling for cheapies, didnt help.

**Comment by yzyhk904** [comment]
See README! You can change the samplerate to be 192 kHz or 48 kHz while decreasing audio quality for usual music apps. Or disable this module in the Magisk manager and reboot, then you can revert the samplerate.

This module itself already includes the cheapies, and has no effect at all.

**Comment by yabo-boye** [comment]
Id love to have an option to disable the effects of this module on internal speakers,  then I can leave it always on.

Otherwise ill do what you said.

Thank you!

**Comment by yabo-boye** [comment]
I changed sample rate to 192000 and patchclearlock to default but now my alarms dont sound. What could be the issue there?

I dont listen to any music files above 96kHz should I try that instead?

**Comment by yzyhk904** [comment]
The issue is for your apps, but not for this module. This module only triggers the issue.

Use another alarm app? My alarm app (pre-installed default one) works even for 384 kHz. Or use 48000 Hz only for internal speakers?

I recommend up-sampling to the Max. samplerate of your DAC. My module uses far better re-sampling than that (or over-sampling) of very expensive DAC's. Bit-perfect is meaningless!

**Comment by yabo-boye** [comment]
Maybe its some limitation of lineage 14 on my s20fe

How can I use 48000 for internal speakers and Max for the rest? Or even a different one also for Bluetooth as using SBC also has limitations,  then only DAC in 384

**Comment by yzyhk904** [comment]
See README! You can change.

It isn't lineageos limitation, but depends on your apps. Both possible max. samplerate of USB and BT are detected automatically because this module doesn't use any offload drivers except Tensor devices.
